- 👋 Hi, I’m kelly. @mekteck15678
- 👀 I’m interested in traveling family learning....
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on something that matters  ...
- 📫 How to reach me  kikecotix@gmail.com...

<!---
mekteck15678/mekteck15678 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
